### ISSUE TITLE
Run Inference Without Docker?

### ISSUE THREAD

**Issue by venkatesh-narayan** [microsoft/REINA#2]
Hi! 

So I've already used the docker command (under `Usage 1`) to train and evaluate my model with REINA, and I have all the outputs from that. For further use, is it possible to do

`export HF_DATASETS_CACHE=/home/reina/data; export TRANSFORMERS_CACHE=/home/reina/cache` 
`python run_summarization.py ...` 

on my local `run_summarization.py` (ie, without using the docker command)? 

Also, is Lucene needed for inference? My guess is that it isn't, because it seems like when you have the REINA dataset in cache, all `reina()` does is load that dataset, and then HuggingFace's `Trainer` takes care of the rest, but want to confirm.

**Comment by shuohangwang** [comment]
Thank you for your interest in this work!

Yeah, if you have the data on disk, no need Lucene anymore: ) BTW, you could also try step1 of usage2 to get the data first. Then you could run your own Seq2Seq model based on step1 output : )

Thanks,
Shuohang
